/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package QLBH.Panel;

import QLBH.myFunction;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giaan
 */
public class QLCTHD extends javax.swing.JDialog {

    Double TongHD = 0d;
    int SHD;
    
    private void loadCBB(){

        Connection con = myFunction.getConnection();
        
        try{
        PreparedStatement pst = con.prepareStatement("select MASP, TENSP, NUOCSX from SANPHAM");
        ResultSet rs =  pst.executeQuery();       
        
        while(rs.next()){
            String MASP = rs.getString("MASP");
            String TENSP = rs.getString("TENSP");
            String NUOCSX = rs.getString("NUOCSX");
            
            cbbAddSP.addItem(myFunction.mergeIdName(MASP,TENSP,NUOCSX));
        }
        con.close();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void loadData(String sohd){
        SHD = Integer.parseInt(sohd);
        lblSHD.setText(sohd);
        Connection con = myFunction.getConnection();
        try{
        String query = "select CTHD.MASP, TENSP, DVT, GIA, SL, NUOCSX from HOADON HD, CTHD, SANPHAM SP where HD.SOHD = CTHD.SOHD and CTHD.MASP = SP.MASP and HD.SOHD = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, String.valueOf(sohd));
        ResultSet rs =  pst.executeQuery();
        
        DefaultTableModel tbModel = (DefaultTableModel)jtbData.getModel();
        tbModel.setRowCount(0);
        while(rs.next()){
            String SOHD = rs.getString("MASP");
            String MASP = rs.getString("TENSP");
            String TENSP = rs.getString("NUOCSX");
            String TRIGIA = myFunction.moneyCompact(rs.getString("GIA"));
            String DVT = rs.getString("DVT");
            String SL = rs.getString("SL");
            
            Double Tong = myFunction.moneytoDouble(rs.getString("GIA")) * Double.parseDouble(SL);  
            
            String data[] = {SOHD,MASP,TENSP,TRIGIA,DVT,SL,myFunction.moneyCompact(String.valueOf(Tong))};
            tbModel.addRow(data);
            TongHD+=Tong;
        }
        lblTong.setText(myFunction.moneyCompact(String.valueOf(TongHD)));
        con.close();
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public QLCTHD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        loadCBB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblSOHD = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btbOK = new javax.swing.JButton();
        cbbAddSP = new javax.swing.JComboBox<>();
        txtSL = new javax.swing.JTextField();
        lblDVT = new javax.swing.JLabel();
        editDialog = new javax.swing.JDialog();
        lblSOHD1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btbOK1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDVT1 = new javax.swing.JLabel();
        txtEditSL = new javax.swing.JTextField();
        txtEditSP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbData = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblTitelTong = new javax.swing.JLabel();
        lblTong = new javax.swing.JLabel();
        lblSHD = new javax.swing.JLabel();

        addDialog.setTitle("Thêm Chi Tiết Hóa Đơn");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Thêm Chi Tiết Cho Hóa Đơn:");

        lblSOHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSOHD.setForeground(new java.awt.Color(0, 204, 204));

        jLabel3.setText("Sản Phẩm :");

        jLabel4.setText("Số Lượng : ");

        btbOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/Actions-16.png"))); // NOI18N
        btbOK.setText("Xác Nhận");
        btbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDialogLayout = new javax.swing.GroupLayout(addDialog.getContentPane());
        addDialog.getContentPane().setLayout(addDialogLayout);
        addDialogLayout.setHorizontalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addDialogLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblSOHD)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2)))
                    .addGroup(addDialogLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addDialogLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDVT))
                            .addGroup(addDialogLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbbAddSP, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(addDialogLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(btbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addDialogLayout.setVerticalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblSOHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbAddSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDVT))
                .addGap(30, 30, 30)
                .addComponent(btbOK)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        lblSOHD1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSOHD1.setForeground(new java.awt.Color(0, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Thay Đổi Chi Tiết Cho Hóa Đơn:");

        btbOK1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/Actions-16.png"))); // NOI18N
        btbOK1.setText("Xác Nhận");
        btbOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbOK1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Số Lượng : ");

        jLabel7.setText("Sản Phẩm :");

        javax.swing.GroupLayout editDialogLayout = new javax.swing.GroupLayout(editDialog.getContentPane());
        editDialog.getContentPane().setLayout(editDialogLayout);
        editDialogLayout.setHorizontalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editDialogLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(lblSOHD1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator3)))
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editDialogLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtEditSL, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDVT1))
                            .addGroup(editDialogLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtEditSP, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(editDialogLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(btbOK1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editDialogLayout.setVerticalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblSOHD1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEditSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEditSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDVT1))
                .addGap(30, 30, 30)
                .addComponent(btbOK1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chi Tiết Hóa Đơn");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Chi Tiết Hóa Đơn:");

        jtbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Nước SX", "Trị Giá", "ĐVT", "Số Lượng", "Tổng Giá"
            }
        ));
        jScrollPane1.setViewportView(jtbData);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/add.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/edit.png"))); // NOI18N
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/delete.png"))); // NOI18N
        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/clóe-16.png"))); // NOI18N
        jButton4.setText("Ðóng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        lblTitelTong.setForeground(new java.awt.Color(255, 51, 51));
        lblTitelTong.setText("Tổng :");

        lblTong.setForeground(new java.awt.Color(255, 51, 0));

        lblSHD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSHD.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitelTong)
                        .addGap(18, 18, 18)
                        .addComponent(lblTong, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSHD)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitelTong)
                    .addComponent(lblTong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lblSOHD.setText(String.valueOf(SHD));
        addDialog.pack();
        addDialog.setSize(460, 300);
        addDialog.setLocationRelativeTo(null);
        addDialog.setAlwaysOnTop(true);
        addDialog.setModal(true);
        addDialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbOKActionPerformed
        Connection con = myFunction.getConnection();
        try{
        String query = "INSERT INTO CTHD VALUES (?,?,?)";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, String.valueOf(SHD));
        pst.setString(2, myFunction.getID(String.valueOf(cbbAddSP.getSelectedItem())));
        pst.setString(3, txtSL.getText());


        pst.executeUpdate();
        JOptionPane.showMessageDialog(addDialog, "Ðã thêm thành công!");
        loadData(String.valueOf(SHD));
        con.close();
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btbOKActionPerformed

    private void btbOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbOK1ActionPerformed
        Connection con = myFunction.getConnection();
        try{
        String query = "UPDATE CTHD SET SL = ? WHERE SOHD = ? and MASP = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, txtEditSL.getText());
        pst.setString(2, String.valueOf(SHD));
        pst.setString(3, myFunction.getID(txtEditSP.getText()));

        pst.executeUpdate();
        JOptionPane.showMessageDialog(editDialog, "Ðã cập nhật thành công!");
        loadData(String.valueOf(SHD));
        editDialog.dispose();
        con.close();
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            JOptionPane.showMessageDialog(editDialog, e);
        }
    }//GEN-LAST:event_btbOK1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lblSOHD1.setText(String.valueOf(SHD));
        editDialog.pack();
        editDialog.setSize(460, 300);
        txtEditSP.setEnabled(false);
        
        DefaultTableModel recordModel = (DefaultTableModel)jtbData.getModel();
        int selectdRow = jtbData.getSelectedRow();
        if(selectdRow==-1) JOptionPane.showMessageDialog(null, "Hãy chọn dữ liệu cần thay đổi!" ,"Thông Báo",HEIGHT);
        else{
            txtEditSP.setText(myFunction.mergeIdName(recordModel.getValueAt(selectdRow, 0).toString(),recordModel.getValueAt(selectdRow, 1).toString(),recordModel.getValueAt(selectdRow, 2).toString()));
            txtEditSL.setText(recordModel.getValueAt(selectdRow, 5).toString());
            
            editDialog.setLocationRelativeTo(null);
            editDialog.setAlwaysOnTop(true);
            editDialog.setModal(true);
            editDialog.setVisible(true);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel recordModel = (DefaultTableModel)jtbData.getModel();
        int selectdRow = jtbData.getSelectedRow();
        if(selectdRow==-1) JOptionPane.showMessageDialog(null, "Hãy chọn dữ liệu cần Xóa!" ,"Thông Báo",HEIGHT);
        else{
        int response = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?", "Xác Nhận Xóa", WIDTH, HEIGHT);
        if(response==JOptionPane.YES_OPTION)
        {
        Connection con = myFunction.getConnection();
        try{
        String query = "DELETE FROM CTHD WHERE SOHD = ? and MASP = ?";
        PreparedStatement pst = con.prepareStatement(query);
        
        pst.setString(1, String.valueOf(SHD));
        pst.setString(2, recordModel.getValueAt(selectdRow, 0).toString());
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Ðã xóa thành công!");
        loadData(String.valueOf(SHD));
        con.close();
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            JOptionPane.showMessageDialog(editDialog, e);
        }
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLCTHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLCTHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLCTHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLCTHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QLCTHD dialog = new QLCTHD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog addDialog;
    private javax.swing.JButton btbOK;
    private javax.swing.JButton btbOK1;
    private javax.swing.JComboBox<String> cbbAddSP;
    private javax.swing.JDialog editDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jtbData;
    private javax.swing.JLabel lblDVT;
    private javax.swing.JLabel lblDVT1;
    private javax.swing.JLabel lblSHD;
    private javax.swing.JLabel lblSOHD;
    private javax.swing.JLabel lblSOHD1;
    private javax.swing.JLabel lblTitelTong;
    private javax.swing.JLabel lblTong;
    private javax.swing.JTextField txtEditSL;
    private javax.swing.JTextField txtEditSP;
    private javax.swing.JTextField txtSL;
    // End of variables declaration//GEN-END:variables
}
