/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLBH.Panel;

import QLBH.myFunction;
import static com.microsoft.sqlserver.jdbc.StringUtils.isNumeric;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;


public class QLHD extends javax.swing.JPanel {
    
    private QLCTHD CTHD;
    
    private void loadData(){
        TableColumnModel columnModel = jtbData.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(40);
        columnModel.getColumn(1).setPreferredWidth(70);
        columnModel.getColumn(2).setPreferredWidth(160);
        columnModel.getColumn(3).setPreferredWidth(160);
        columnModel.getColumn(4).setPreferredWidth(100);
        
        Connection con = myFunction.getConnection();
        
        try{
        PreparedStatement pst = con.prepareStatement("select SOHD, NGHD, HD.MAKH, KH.HOTEN as TENKH, HD.MANV, NV.HOTEN as TENNV, TRIGIA from HOADON HD left join KHACHHANG KH on  HD.MAKH = KH.MAKH  left join  NHANVIEN NV on HD.MANV = NV.MANV");
        ResultSet rs =  pst.executeQuery();       
        
        DefaultTableModel tbModel = (DefaultTableModel)jtbData.getModel();        
        tbModel.setRowCount(0);
        while(rs.next()){
            String SOHD = rs.getString("SOHD");
            String NGHD = myFunction.dateLongtoShort(rs.getString("NGHD"));
            String MAKH = rs.getString("MAKH");
            String TENKH = rs.getString("TENKH");
            String KH = myFunction.mergeIdName(MAKH,TENKH);
            String MANV = rs.getString("MANV");
            String TENNV = rs.getString("TENNV");
            String NV = myFunction.mergeIdName(MANV,TENNV);
            String TRIGIA = myFunction.moneyCompact(rs.getString("TRIGIA"));
            
            String data[] = {SOHD,NGHD,KH,NV,TRIGIA};
            tbModel.addRow(data);
        }
        con.close();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    } 
    
    private void clear(){
        txtSearch.setText("");
        txtAddSOHD.setText("");
        txtAddNGHD.setText("");
        txtAddGIA.setText("");
        txtEditSOHD.setText("");
        txtEditNGHD.setText("");
        txtEditGIA.setText("");

        loadData();  
    }
    
    private void loadCBB(){
        cbbAddKH.addItem("");
        cbbEditKH.addItem("");
        Connection con = myFunction.getConnection();
        
        try{
        PreparedStatement pst = con.prepareStatement("select MAKH, HOTEN from KHACHHANG");
        ResultSet rs =  pst.executeQuery();       
        
        while(rs.next()){
            String MAKH = rs.getString("MAKH");
            String HOTEN = rs.getString("HOTEN");
            
            cbbAddKH.addItem(myFunction.mergeIdName(MAKH,HOTEN));
            cbbEditKH.addItem(myFunction.mergeIdName(MAKH,HOTEN));
        }
        
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        try{
        PreparedStatement pst = con.prepareStatement("select MANV, HOTEN from NHANVIEN");
        ResultSet rs =  pst.executeQuery();       
        
        while(rs.next()){
            String MANV = rs.getString("MANV");
            String HOTEN = rs.getString("HOTEN");
            
            cbbAddNV.addItem(myFunction.mergeIdName(MANV,HOTEN));
            cbbEditNV.addItem(myFunction.mergeIdName(MANV,HOTEN));
        }
        con.close();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public QLHD() {
        initComponents();
        loadData();
        jtbData.setDefaultEditor(Object.class, null);
        loadCBB();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDialog = new javax.swing.JDialog();
        jlbAddSOHD = new javax.swing.JLabel();
        jlbAddNGHD = new javax.swing.JLabel();
        jlbAddMAKH = new javax.swing.JLabel();
        jlbAddMANV = new javax.swing.JLabel();
        jlbAddGIA = new javax.swing.JLabel();
        txtAddSOHD = new javax.swing.JTextField();
        txtAddNGHD = new javax.swing.JTextField();
        txtAddGIA = new javax.swing.JTextField();
        btnAddConfirm = new javax.swing.JButton();
        cbbAddKH = new javax.swing.JComboBox<>();
        cbbAddNV = new javax.swing.JComboBox<>();
        editDialog = new javax.swing.JDialog();
        jlbEditSOHD = new javax.swing.JLabel();
        jlbEditNGHD = new javax.swing.JLabel();
        jlbEditMAKH = new javax.swing.JLabel();
        jlbEditMANV = new javax.swing.JLabel();
        jlbEditGIA = new javax.swing.JLabel();
        txtEditSOHD = new javax.swing.JTextField();
        txtEditNGHD = new javax.swing.JTextField();
        txtEditGIA = new javax.swing.JTextField();
        btnEditConfirm = new javax.swing.JButton();
        cbbEditKH = new javax.swing.JComboBox<>();
        cbbEditNV = new javax.swing.JComboBox<>();
        jlbTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbData = new javax.swing.JTable();
        jplFuntion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnRef = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();

        addDialog.setTitle("Thêm Hóa Đơn");
        addDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                addDialogWindowClosed(evt);
            }
        });

        jlbAddSOHD.setText("Số HĐ:");

        jlbAddNGHD.setText("Ngày HĐ:");

        jlbAddMAKH.setText("Mã KH:");

        jlbAddMANV.setText("Mã NV:");

        jlbAddGIA.setText("Trị Giá:");

        btnAddConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/check-16.png"))); // NOI18N
        btnAddConfirm.setText("Xác Nhận");
        btnAddConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDialogLayout = new javax.swing.GroupLayout(addDialog.getContentPane());
        addDialog.getContentPane().setLayout(addDialogLayout);
        addDialogLayout.setHorizontalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbAddMANV)
                    .addComponent(jlbAddMAKH)
                    .addComponent(jlbAddNGHD)
                    .addComponent(jlbAddSOHD)
                    .addComponent(jlbAddGIA))
                .addGap(30, 30, 30)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAddGIA, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(txtAddNGHD)
                    .addComponent(txtAddSOHD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbAddKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbAddNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(addDialogLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btnAddConfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addDialogLayout.setVerticalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddSOHD)
                    .addComponent(txtAddSOHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddNGHD)
                    .addComponent(txtAddNGHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddMAKH)
                    .addComponent(cbbAddKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddMANV)
                    .addComponent(cbbAddNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddGIA)
                    .addComponent(txtAddGIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddConfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editDialog.setTitle("Thay Đổi Hóa Đơn");
        editDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                editDialogWindowClosed(evt);
            }
        });

        jlbEditSOHD.setText("Số HĐ:");

        jlbEditNGHD.setText("Ngày HĐ:");

        jlbEditMAKH.setText("Mã KH:");

        jlbEditMANV.setText("Mã NV:");

        jlbEditGIA.setText("Trị Giá:");

        btnEditConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/check-16.png"))); // NOI18N
        btnEditConfirm.setText("Xác Nhận");
        btnEditConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editDialogLayout = new javax.swing.GroupLayout(editDialog.getContentPane());
        editDialog.getContentPane().setLayout(editDialogLayout);
        editDialogLayout.setHorizontalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbEditMANV)
                    .addComponent(jlbEditMAKH)
                    .addComponent(jlbEditNGHD)
                    .addComponent(jlbEditSOHD)
                    .addComponent(jlbEditGIA))
                .addGap(30, 30, 30)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEditGIA)
                    .addComponent(txtEditNGHD)
                    .addComponent(txtEditSOHD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbEditKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbEditNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDialogLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(btnEditConfirm)
                .addGap(136, 136, 136))
        );
        editDialogLayout.setVerticalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditSOHD)
                    .addComponent(txtEditSOHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditNGHD)
                    .addComponent(txtEditNGHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditMAKH)
                    .addComponent(cbbEditKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditMANV)
                    .addComponent(cbbEditNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditGIA)
                    .addComponent(txtEditGIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEditConfirm)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jlbTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbTitle.setForeground(new java.awt.Color(0, 153, 153));
        jlbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitle.setText("QUẢN LÝ HÓA ĐƠN");

        jtbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số Hóa Đơn", "Ngày Hóa Đơn", "Khách Hàng", "Nhân Viên", "Trị Giá"
            }
        ));
        jScrollPane1.setViewportView(jtbData);

        jplFuntion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tìm Kiếm:");

        txtSearch.setPreferredSize(new java.awt.Dimension(64, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/search.png"))); // NOI18N
        jButton1.setText("Tìm Kiếm");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/add.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setPreferredSize(new java.awt.Dimension(100, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/edit.png"))); // NOI18N
        btnMod.setText("Sửa");
        btnMod.setPreferredSize(new java.awt.Dimension(100, 30));
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/delete.png"))); // NOI18N
        btnDel.setText("Xóa");
        btnDel.setPreferredSize(new java.awt.Dimension(100, 30));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnRef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/clear.png"))); // NOI18N
        btnRef.setText("Làm Mới");
        btnRef.setPreferredSize(new java.awt.Dimension(100, 30));
        btnRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefActionPerformed(evt);
            }
        });

        btnDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/detail-16.png"))); // NOI18N
        btnDetail.setText("Chi Tiết");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplFuntionLayout = new javax.swing.GroupLayout(jplFuntion);
        jplFuntion.setLayout(jplFuntionLayout);
        jplFuntionLayout.setHorizontalGroup(
            jplFuntionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplFuntionLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addComponent(jSeparator2)
            .addGroup(jplFuntionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetail)
                .addGap(18, 18, 18)
                .addComponent(btnRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplFuntionLayout.setVerticalGroup(
            jplFuntionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplFuntionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplFuntionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jplFuntionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                    .addComponent(jplFuntion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jplFuntion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        txtAddNGHD.setText(myFunction.getCurrentDate());
        addDialog.pack();
        addDialog.setSize(375, 350);
        addDialog.setLocationRelativeTo(null);
        addDialog.setAlwaysOnTop(true);
        addDialog.setModal(true);
        addDialog.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAddConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddConfirmActionPerformed
        StringBuilder sbError = new StringBuilder();
        if(txtAddSOHD.getText().hashCode() == 0) sbError.append("Yêu cầu có Số Hóa Đơn! \n");
        if(txtAddSOHD.getText().length()>4) sbError.append("Số Hóa Đơn tối đa 4 kí tự, ví dụ 1001 1002 ... \n");
        if((!myFunction.isVNDate(txtAddNGHD.getText())&&!txtAddNGHD.getText().equals(""))) sbError.append("Ngày vào làm không đúng, hãy nhập dạng dd/MM/yyyy ex: 25/12/2020");
               
        Connection con = myFunction.getConnection();
        try{
            if(sbError.length()>0) JOptionPane.showMessageDialog(addDialog, sbError ,"Thông Báo",HEIGHT);
        else{
            String query;
            if(!myFunction.getID(String.valueOf(cbbAddKH.getSelectedItem())).equals("")) query = "INSERT INTO HOADON(SOHD,NGHD,MANV,TRIGIA,MAKH) VALUES (?,?,?,?,?)";
            else query = "INSERT INTO HOADON(SOHD,NGHD,MANV,TRIGIA) VALUES (?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, txtAddSOHD.getText());
            pst.setString(2, myFunction.dateShorttoLongto(txtAddNGHD.getText()));
            pst.setString(3, myFunction.getID(String.valueOf(cbbAddNV.getSelectedItem())));
            pst.setString(4, txtAddGIA.getText());
            if(!myFunction.getID(String.valueOf(cbbAddKH.getSelectedItem())).equals("")) pst.setString(5, myFunction.getID(String.valueOf(cbbAddKH.getSelectedItem())));

            System.out.println(myFunction.getID(String.valueOf(cbbAddKH.getSelectedItem())));
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(addDialog, "Ðã thêm thành công!");
            clear();
            con.close();
            addDialog.dispose();
        }
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            JOptionPane.showMessageDialog(addDialog, e);
        }
    }//GEN-LAST:event_btnAddConfirmActionPerformed

    private void addDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_addDialogWindowClosed
        addDialog.dispose();
    }//GEN-LAST:event_addDialogWindowClosed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        editDialog.pack();
        editDialog.setSize(375, 350);
        editDialog.setAlwaysOnTop(true);
        editDialog.setModal(true);
        editDialog.setLocationRelativeTo(this);
        txtEditSOHD.setEnabled(false);
        
        DefaultTableModel recordModel = (DefaultTableModel)jtbData.getModel();
        int selectdRow = jtbData.getSelectedRow();
        if(selectdRow==-1) JOptionPane.showMessageDialog(null, "Hãy chọn dữ liệu cần thay đổi!" ,"Thông Báo",HEIGHT);
        else{
            txtEditSOHD.setText(recordModel.getValueAt(selectdRow, 0).toString());
            if(recordModel.getValueAt(selectdRow, 1)!=null)
            txtEditNGHD.setText(recordModel.getValueAt(selectdRow, 1).toString());
            cbbEditKH.setSelectedItem(recordModel.getValueAt(selectdRow, 2));
            cbbEditNV.setSelectedItem(recordModel.getValueAt(selectdRow, 3));
            if(recordModel.getValueAt(selectdRow, 4)!=null)
            txtEditGIA.setText(recordModel.getValueAt(selectdRow, 4).toString());


            editDialog.setAlwaysOnTop(true);
            editDialog.setModal(true);
            editDialog.setLocationRelativeTo(this);

            editDialog.setVisible(true);
        }
    }//GEN-LAST:event_btnModActionPerformed

    private void editDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_editDialogWindowClosed
        editDialog.dispose();
    }//GEN-LAST:event_editDialogWindowClosed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        DefaultTableModel recordModel = (DefaultTableModel)jtbData.getModel();
        int selectdRow = jtbData.getSelectedRow();
        if(selectdRow==-1) JOptionPane.showMessageDialog(null, "Hãy chọn dữ liệu cần xóa!" ,"Thông Báo",HEIGHT);
        else{
        int response = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?", "Xác Nhận Xóa", WIDTH, HEIGHT);
        if(response==JOptionPane.YES_OPTION)
        {
        Connection con = myFunction.getConnection();
        try{
        String query = "DELETE FROM HOADON WHERE SOHD=?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, recordModel.getValueAt(selectdRow, 0).toString());
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Ðã xóa thành công!");
        loadData();
        con.close();
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefActionPerformed
        clear();
    }//GEN-LAST:event_btnRefActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = myFunction.getConnection();
        try{
        String query = "select * from HOADON where SOHD = ? or MAKH = ? or MANV = ?";
        PreparedStatement pst = con.prepareStatement(query);
        if(isNumeric(txtSearch.getText())) pst.setString(1, txtSearch.getText());
        else pst.setString(1, null);
        pst.setString(2, txtSearch.getText());
        pst.setString(3, txtSearch.getText());
        
        ResultSet rs =  pst.executeQuery();
        DefaultTableModel rsModel = (DefaultTableModel)jtbData.getModel();
        rsModel.setRowCount(0);
        while(rs.next()){
            String SOHD = rs.getString("SOHD");
            String NGHD = myFunction.dateLongtoShort(rs.getString("NGHD"));
            String MAKH = rs.getString("MAKH");
            String MANV = rs.getString("MANV");
            String TRIGIA = myFunction.moneyCompact(rs.getString("TRIGIA"));
            
            String data[] = {SOHD,NGHD,MAKH,MANV,TRIGIA};
            rsModel.addRow(data);
        }
        con.close();
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEditConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditConfirmActionPerformed
        StringBuilder sbError = new StringBuilder();
        if(txtEditSOHD.getText().hashCode() == 0) sbError.append("Yêu cầu có Số Hóa Đơn! \n");
        if(txtEditSOHD.getText().length()>4) sbError.append("Số Hóa Đơn tối đa 4 kí tự, ví dụ 1001 1002 ... \n");
        if((!myFunction.isVNDate(txtAddNGHD.getText())&&!txtAddNGHD.getText().equals(""))) sbError.append("Ngày vào làm không đúng, hãy nhập dạng dd/MM/yyyy ex: 25/12/2020");
       
        Connection con = myFunction.getConnection();
        if(sbError.length()>0) JOptionPane.showMessageDialog(editDialog, sbError ,"Thông Báo",HEIGHT);
        else{
            try{
                String query = "UPDATE HOADON SET NGHD = ?, MAKH = ?, MANV = ?,TRIGIA = ? WHERE SOHD = ?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, myFunction.dateShorttoLongto(txtEditNGHD.getText()));
                pst.setString(2, myFunction.getID(String.valueOf(cbbEditKH.getSelectedItem())));
                pst.setString(3, myFunction.getID(String.valueOf(cbbEditNV.getSelectedItem())));
                pst.setString(4, txtEditGIA.getText());
                pst.setString(5, txtEditSOHD.getText());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(editDialog, "Ðã cập nhật thành công!");
                clear();
                con.close();
                editDialog.dispose();
            }
            // Handle any errors that may have occurred.
            catch (SQLException e) {
                JOptionPane.showMessageDialog(editDialog, e);
            }
        }
    }//GEN-LAST:event_btnEditConfirmActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        DefaultTableModel recordModel = (DefaultTableModel)jtbData.getModel();
        int selectdRow = jtbData.getSelectedRow();
        if(selectdRow==-1) JOptionPane.showMessageDialog(null, "Hãy chọn dữ liệu cần xem!" ,"Thông Báo",HEIGHT);
        else{
            ;
            
            CTHD = new QLCTHD(null,true);
            CTHD.loadData(recordModel.getValueAt(selectdRow, 0).toString());
            CTHD.setVisible(true);
        }
    }//GEN-LAST:event_btnDetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog addDialog;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddConfirm;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnEditConfirm;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnRef;
    private javax.swing.JComboBox<String> cbbAddKH;
    private javax.swing.JComboBox<String> cbbAddNV;
    private javax.swing.JComboBox<String> cbbEditKH;
    private javax.swing.JComboBox<String> cbbEditNV;
    private javax.swing.JDialog editDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlbAddGIA;
    private javax.swing.JLabel jlbAddMAKH;
    private javax.swing.JLabel jlbAddMANV;
    private javax.swing.JLabel jlbAddNGHD;
    private javax.swing.JLabel jlbAddSOHD;
    private javax.swing.JLabel jlbEditGIA;
    private javax.swing.JLabel jlbEditMAKH;
    private javax.swing.JLabel jlbEditMANV;
    private javax.swing.JLabel jlbEditNGHD;
    private javax.swing.JLabel jlbEditSOHD;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JPanel jplFuntion;
    private javax.swing.JTable jtbData;
    private javax.swing.JTextField txtAddGIA;
    private javax.swing.JTextField txtAddNGHD;
    private javax.swing.JTextField txtAddSOHD;
    private javax.swing.JTextField txtEditGIA;
    private javax.swing.JTextField txtEditNGHD;
    private javax.swing.JTextField txtEditSOHD;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
