/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLBH.Panel;

import QLBH.myFunction;
import static com.microsoft.sqlserver.jdbc.StringUtils.isNumeric;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;


public class QLKH extends javax.swing.JPanel {
    

    private void loadData(){
        TableColumnModel columnModel = jtbData.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(1).setPreferredWidth(120);
        columnModel.getColumn(2).setPreferredWidth(230);
        columnModel.getColumn(3).setPreferredWidth(80);
        columnModel.getColumn(4).setPreferredWidth(80);
        columnModel.getColumn(5).setPreferredWidth(80);
        columnModel.getColumn(3).setPreferredWidth(80);
        columnModel.getColumn(4).setPreferredWidth(80);
        
        Connection con = myFunction.getConnection();
        
        try{
        PreparedStatement pst = con.prepareStatement("select * from KHACHHANG");
        ResultSet rs =  pst.executeQuery();       
        
        DefaultTableModel tbModel = (DefaultTableModel)jtbData.getModel();        
        tbModel.setRowCount(0);
        while(rs.next()){
            String MANV = rs.getString("MAKH");
            String HOTEN = rs.getString("HOTEN");
            String DIACHI = rs.getString("DCHI");
            String SDT = rs.getString("SODT");
            String NGSINH = myFunction.dateLongtoShort(rs.getString("NGSINH"));
            String NGDK = myFunction.dateLongtoShort(rs.getString("NGDK"));
            String DOANHSO = myFunction.moneyCompact(rs.getString("DOANHSO"));
            String LOAIKH = rs.getString("LOAIKH");
            
            String data[] = {MANV,HOTEN,DIACHI,SDT,NGSINH,NGDK,DOANHSO,LOAIKH};
            tbModel.addRow(data);
        }
        con.close();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    } 
    
    private void clear(){
        txtSearch.setText("");
        txtAddMAKH.setText("");
        txtAddHOTEN.setText("");
        txtAddDCHI.setText("");
        txtAddSODT.setText("");
        txtAddNGSINH.setText("");
        txtAddNGDK.setText("");
        txtAddDOANHSO.setText("");
        txtAddLOAIKH.setText("");
        txtEditMAKH.setText("");
        txtEditHOTEN.setText("");
        txtEditDCHI.setText("");
        txtEditSODT.setText("");
        txtEditNGSINH.setText("");
        txtEditNGDK.setText("");
        txtEditDOANHSO.setText("");
        txtEditLOAIKH.setText("");
        loadData();  
    }
    
    public QLKH() {
        initComponents();
        loadData();
        jtbData.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDialog = new javax.swing.JDialog();
        jlbAddMAKH = new javax.swing.JLabel();
        jlbAddHOTEN = new javax.swing.JLabel();
        jlbAddDCHI = new javax.swing.JLabel();
        jlbAddSODT = new javax.swing.JLabel();
        jlbAddNGSINH = new javax.swing.JLabel();
        jlbAddNGDK = new javax.swing.JLabel();
        jlbAddDOANHSO = new javax.swing.JLabel();
        jlbAddLOAIKH = new javax.swing.JLabel();
        txtAddMAKH = new javax.swing.JTextField();
        txtAddHOTEN = new javax.swing.JTextField();
        txtAddDCHI = new javax.swing.JTextField();
        txtAddSODT = new javax.swing.JTextField();
        txtAddNGSINH = new javax.swing.JTextField();
        txtAddNGDK = new javax.swing.JTextField();
        txtAddDOANHSO = new javax.swing.JTextField();
        txtAddLOAIKH = new javax.swing.JTextField();
        btnAddConfirm = new javax.swing.JButton();
        editDialog = new javax.swing.JDialog();
        jlbEditMAKH = new javax.swing.JLabel();
        jlbEditHOTEN = new javax.swing.JLabel();
        jlbEditDCHI = new javax.swing.JLabel();
        jlbEditSODT = new javax.swing.JLabel();
        jlbEditNGSINH = new javax.swing.JLabel();
        jlbEditNGDK = new javax.swing.JLabel();
        jlbEditDOANHSO = new javax.swing.JLabel();
        jlbEditLOAIKH = new javax.swing.JLabel();
        txtEditMAKH = new javax.swing.JTextField();
        txtEditHOTEN = new javax.swing.JTextField();
        txtEditDCHI = new javax.swing.JTextField();
        txtEditSODT = new javax.swing.JTextField();
        txtEditNGSINH = new javax.swing.JTextField();
        txtEditNGDK = new javax.swing.JTextField();
        txtEditDOANHSO = new javax.swing.JTextField();
        txtEditLOAIKH = new javax.swing.JTextField();
        btnEditConfirm = new javax.swing.JButton();
        jlbTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbData = new javax.swing.JTable();
        jplFuntion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnRef = new javax.swing.JButton();

        addDialog.setTitle("Thêm Khách Hàng");
        addDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                addDialogWindowClosed(evt);
            }
        });

        jlbAddMAKH.setText("Mã KH:");

        jlbAddHOTEN.setText("Họ Tên:");

        jlbAddDCHI.setText("Địa Chỉ:");

        jlbAddSODT.setText("Số ĐT:");

        jlbAddNGSINH.setText("Ngày Sinh:");

        jlbAddNGDK.setText("Ngày ĐK:");

        jlbAddDOANHSO.setText("Doanh Số:");

        jlbAddLOAIKH.setText("Loại KH:");

        btnAddConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/check-16.png"))); // NOI18N
        btnAddConfirm.setText("Xác Nhận");
        btnAddConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDialogLayout = new javax.swing.GroupLayout(addDialog.getContentPane());
        addDialog.getContentPane().setLayout(addDialogLayout);
        addDialogLayout.setHorizontalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addDialogLayout.createSequentialGroup()
                        .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbAddLOAIKH)
                            .addComponent(jlbAddDOANHSO)
                            .addComponent(jlbAddNGDK)
                            .addComponent(jlbAddNGSINH))
                        .addGap(18, 18, 18)
                        .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddDOANHSO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtAddNGDK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAddNGSINH)
                            .addComponent(txtAddLOAIKH)))
                    .addGroup(addDialogLayout.createSequentialGroup()
                        .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbAddSODT)
                            .addComponent(jlbAddDCHI)
                            .addComponent(jlbAddHOTEN)
                            .addComponent(jlbAddMAKH))
                        .addGap(34, 34, 34)
                        .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddHOTEN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAddDCHI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAddSODT)
                            .addComponent(txtAddMAKH))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddConfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addDialogLayout.setVerticalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddMAKH)
                    .addComponent(txtAddMAKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddHOTEN)
                    .addComponent(txtAddHOTEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddDCHI)
                    .addComponent(txtAddDCHI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddSODT)
                    .addComponent(txtAddSODT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddNGSINH)
                    .addComponent(txtAddNGSINH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddNGDK)
                    .addComponent(txtAddNGDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddDOANHSO)
                    .addComponent(txtAddDOANHSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddLOAIKH)
                    .addComponent(txtAddLOAIKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddConfirm)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        editDialog.setTitle("Thay đổi thông tin Khách Hàng");
        editDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                editDialogWindowClosed(evt);
            }
        });

        jlbEditMAKH.setText("Mã KH:");

        jlbEditHOTEN.setText("Họ Tên:");

        jlbEditDCHI.setText("Địa Chỉ:");

        jlbEditSODT.setText("Số ĐT:");

        jlbEditNGSINH.setText("Ngày Sinh:");

        jlbEditNGDK.setText("Ngày ĐK:");

        jlbEditDOANHSO.setText("Doanh Số:");

        jlbEditLOAIKH.setText("Loại KH:");

        btnEditConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/check-16.png"))); // NOI18N
        btnEditConfirm.setText("Xác Nhận");
        btnEditConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editDialogLayout = new javax.swing.GroupLayout(editDialog.getContentPane());
        editDialog.getContentPane().setLayout(editDialogLayout);
        editDialogLayout.setHorizontalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbEditLOAIKH)
                            .addComponent(jlbEditDOANHSO)
                            .addComponent(jlbEditNGDK)
                            .addComponent(jlbEditNGSINH))
                        .addGap(18, 18, 18)
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditDOANHSO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtEditNGDK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEditNGSINH)
                            .addComponent(txtEditLOAIKH)))
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbEditSODT)
                            .addComponent(jlbEditDCHI)
                            .addComponent(jlbEditHOTEN)
                            .addComponent(jlbEditMAKH))
                        .addGap(34, 34, 34)
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditHOTEN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEditDCHI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEditSODT)
                            .addComponent(txtEditMAKH))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditConfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editDialogLayout.setVerticalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditMAKH)
                    .addComponent(txtEditMAKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditHOTEN)
                    .addComponent(txtEditHOTEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditDCHI)
                    .addComponent(txtEditDCHI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditSODT)
                    .addComponent(txtEditSODT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditNGSINH)
                    .addComponent(txtEditNGSINH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditNGDK)
                    .addComponent(txtEditNGDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditDOANHSO)
                    .addComponent(txtEditDOANHSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditLOAIKH)
                    .addComponent(txtEditLOAIKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEditConfirm)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jlbTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbTitle.setForeground(new java.awt.Color(0, 153, 153));
        jlbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitle.setText("QUẢN LÝ KHÁCH HÀNG");

        jtbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Họ Tên", "Địa Chỉ", "Số Điện Thoại", "Ngày Sinh", "Ngày ĐK", "Doanh Số", "Loại KH"
            }
        ));
        jScrollPane1.setViewportView(jtbData);

        jplFuntion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tìm Kiếm:");

        txtSearch.setPreferredSize(new java.awt.Dimension(64, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/search.png"))); // NOI18N
        jButton1.setText("Tìm Kiếm");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/add.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setPreferredSize(new java.awt.Dimension(100, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/edit.png"))); // NOI18N
        btnMod.setText("Sửa");
        btnMod.setPreferredSize(new java.awt.Dimension(100, 30));
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/delete.png"))); // NOI18N
        btnDel.setText("Xóa");
        btnDel.setPreferredSize(new java.awt.Dimension(100, 30));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnRef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/clear.png"))); // NOI18N
        btnRef.setText("Làm Mới");
        btnRef.setPreferredSize(new java.awt.Dimension(100, 30));
        btnRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplFuntionLayout = new javax.swing.GroupLayout(jplFuntion);
        jplFuntion.setLayout(jplFuntionLayout);
        jplFuntionLayout.setHorizontalGroup(
            jplFuntionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplFuntionLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addComponent(jSeparator2)
            .addGroup(jplFuntionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplFuntionLayout.setVerticalGroup(
            jplFuntionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplFuntionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplFuntionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jplFuntionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(jplFuntion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jplFuntion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addDialog.pack();
        addDialog.setSize(375, 460);
        addDialog.setLocationRelativeTo(null);
        addDialog.setAlwaysOnTop(true);
        addDialog.setModal(true);
        txtAddNGDK.setText(DateTimeFormatter.ofPattern("dd/MM/yyyy").format(LocalDateTime.now()));
        addDialog.setVisible(true);
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAddConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddConfirmActionPerformed
        StringBuilder sbError = new StringBuilder();
        if(txtAddMAKH.getText().hashCode() == 0) sbError.append("Yêu cầu có mã Khách Hàng! \n");
        if(txtAddMAKH.getText().length()>4) sbError.append("Mã Khách Hàng tối đa 4 kí tự, ví dụ NV01 NV02 ... \n");
        if(!isNumeric(txtAddSODT.getText())&&!txtAddSODT.getText().equals("")) sbError.append("Số điện thoại phải là số! \n");
        if((!myFunction.isVNDate(txtAddNGSINH.getText())&&!txtAddNGSINH.getText().equals(""))||(!myFunction.isVNDate(txtAddNGDK.getText())&&!txtAddNGDK.getText().equals(""))) sbError.append("Ngày vào làm không đúng, hãy nhập dạng dd/MM/yyyy ex: 25/12/2020");
        
        Connection con = myFunction.getConnection();
        try{
            if(sbError.length()>0) JOptionPane.showMessageDialog(addDialog, sbError ,"Thông Báo",HEIGHT);
        else{
            String query = "INSERT INTO KHACHHANG VALUES (?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, txtAddMAKH.getText());
            pst.setString(2, txtAddHOTEN.getText());
            pst.setString(3, txtAddDCHI.getText());
            pst.setString(4, txtAddSODT.getText());
            pst.setString(5, myFunction.dateShorttoLongto(txtAddNGSINH.getText()));
            pst.setString(6, myFunction.dateShorttoLongto(txtAddNGDK.getText()));
            pst.setString(7, txtAddDOANHSO.getText());
            pst.setString(8, txtAddLOAIKH.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(addDialog, "Ðã thêm thành công!");
            clear();
            con.close();
            addDialog.dispose();
        }
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            JOptionPane.showMessageDialog(addDialog, e);
        }
    }//GEN-LAST:event_btnAddConfirmActionPerformed

    private void addDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_addDialogWindowClosed
        addDialog.dispose();
    }//GEN-LAST:event_addDialogWindowClosed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        editDialog.pack();
        editDialog.setSize(375, 460);
        editDialog.setAlwaysOnTop(true);
        editDialog.setModal(true);
        editDialog.setLocationRelativeTo(this);
        txtEditMAKH.setEnabled(false);
        
        DefaultTableModel recordModel = (DefaultTableModel)jtbData.getModel();
        int selectdRow = jtbData.getSelectedRow();
        if(selectdRow==-1) JOptionPane.showMessageDialog(null, "Hãy chọn dữ liệu cần thay đổi!" ,"Thông Báo",HEIGHT);
        else{
            txtEditMAKH.setText(recordModel.getValueAt(selectdRow, 0).toString());
            if(recordModel.getValueAt(selectdRow, 1)!=null)
            txtEditHOTEN.setText(recordModel.getValueAt(selectdRow, 1).toString());
            if(recordModel.getValueAt(selectdRow, 2)!=null)
            txtEditDCHI.setText(recordModel.getValueAt(selectdRow, 2).toString());
            if(recordModel.getValueAt(selectdRow, 3)!=null)
            txtEditSODT.setText(recordModel.getValueAt(selectdRow, 3).toString());
            if(recordModel.getValueAt(selectdRow, 4)!=null)
            txtEditNGSINH.setText(recordModel.getValueAt(selectdRow, 4).toString());
            if(recordModel.getValueAt(selectdRow, 5)!=null)
            txtEditNGDK.setText(recordModel.getValueAt(selectdRow, 5).toString());
            if(recordModel.getValueAt(selectdRow, 6)!=null)
            txtEditDOANHSO.setText(recordModel.getValueAt(selectdRow, 6).toString());
            if(recordModel.getValueAt(selectdRow, 7)!=null)
            txtEditLOAIKH.setText(recordModel.getValueAt(selectdRow, 7).toString());

            editDialog.setAlwaysOnTop(true);
            editDialog.setModal(true);
            editDialog.setLocationRelativeTo(this);

            editDialog.setVisible(true);
        }
    }//GEN-LAST:event_btnModActionPerformed

    private void editDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_editDialogWindowClosed
        editDialog.dispose();
    }//GEN-LAST:event_editDialogWindowClosed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        DefaultTableModel recordModel = (DefaultTableModel)jtbData.getModel();
        int selectdRow = jtbData.getSelectedRow();
        if(selectdRow==-1) JOptionPane.showMessageDialog(null, "Hãy chọn dữ liệu cần xóa!" ,"Thông Báo",HEIGHT);
        else{
        int response = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?", "Xác Nhận Xóa", WIDTH, HEIGHT);
        if(response==JOptionPane.YES_OPTION)
        {
        Connection con = myFunction.getConnection();
        try{
        String query = "DELETE FROM KHACHHANG WHERE MAKH=?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, recordModel.getValueAt(selectdRow, 0).toString());
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Ðã xóa thành công!");
        loadData();
        con.close();
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefActionPerformed
        clear();
    }//GEN-LAST:event_btnRefActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = myFunction.getConnection();
        try{
        String query = "select * from KHACHHANG where MAKH = '" + txtSearch.getText() + "' or HOTEN LIKE N'%" + txtSearch.getText() + "%'" ;
        PreparedStatement pst = con.prepareStatement(query);
        ResultSet rs =  pst.executeQuery();
        
        DefaultTableModel rsModel = (DefaultTableModel)jtbData.getModel();
        
        rsModel.setRowCount(0);
        while(rs.next()){
            String MANV = rs.getString("MAKH");
            String HOTEN = rs.getString("HOTEN");
            String DIACHI = rs.getString("DCHI");
            String SDT = rs.getString("SODT");
            String NGSINH = myFunction.dateLongtoShort(rs.getString("NGSINH"));
            String NGDK = myFunction.dateLongtoShort(rs.getString("NGDK"));
            String DOANHSO = myFunction.moneyCompact(rs.getString("DOANHSO"));
            String LOAIKH = rs.getString("LOAIKH");
            
            String data[] = {MANV,HOTEN,DIACHI,SDT,NGSINH,NGDK,DOANHSO,LOAIKH};
            rsModel.addRow(data);
        }
        con.close();
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEditConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditConfirmActionPerformed
        StringBuilder sbError = new StringBuilder();
        if(txtEditMAKH.getText().hashCode() == 0) sbError.append("Yêu cầu có mã Khách Hàng! \n");
        if(txtEditMAKH.getText().length()>4) sbError.append("Mã Khách Hàng tối đa 4 kí tự, ví dụ NV01 NV02 ... \n");
        if(!isNumeric(txtEditSODT.getText())&&!txtAddSODT.getText().equals("")) sbError.append("Số điện thoại phải là số! \n");
        if((!myFunction.isVNDate(txtEditNGSINH.getText())&&!txtEditNGSINH.getText().equals(""))||(!myFunction.isVNDate(txtEditNGDK.getText())&&!txtEditNGDK.getText().equals(""))) sbError.append("Ngày vào làm không đúng, hãy nhập dạng dd/MM/yyyy ex: 25/12/2020");
        
        Connection con = myFunction.getConnection();
        if(sbError.length()>0) JOptionPane.showMessageDialog(editDialog, sbError ,"Thông Báo",HEIGHT);
        else{
        try{
        String query = "UPDATE KHACHHANG SET HOTEN = ?, DCHI = ?, SODT = ?,NGSINH = ?, NGDK = ?, DOANHSO = ?,LOAIKH = ? WHERE MAKH = ?";
        PreparedStatement pst = con.prepareStatement(query);
        System.out.println(pst);
        pst.setString(1, txtEditHOTEN.getText());
        pst.setString(2, txtEditDCHI.getText());
        pst.setString(3, txtEditSODT.getText());
        pst.setString(4, myFunction.dateShorttoLongto(txtEditNGSINH.getText()));
        pst.setString(5, myFunction.dateShorttoLongto(txtEditNGDK.getText()));
        pst.setString(6, txtEditDOANHSO.getText());
        if(txtEditLOAIKH.getText()==null) pst.setString(8, null);
        else pst.setString(7, txtEditLOAIKH.getText());
        pst.setString(8, txtEditMAKH.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(editDialog, "Ðã cập nhật thành công!");
        clear();
        con.close();
        editDialog.dispose();
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            JOptionPane.showMessageDialog(editDialog, e);
        }
        } 
    }//GEN-LAST:event_btnEditConfirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog addDialog;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddConfirm;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEditConfirm;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnRef;
    private javax.swing.JDialog editDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlbAddDCHI;
    private javax.swing.JLabel jlbAddDOANHSO;
    private javax.swing.JLabel jlbAddHOTEN;
    private javax.swing.JLabel jlbAddLOAIKH;
    private javax.swing.JLabel jlbAddMAKH;
    private javax.swing.JLabel jlbAddNGDK;
    private javax.swing.JLabel jlbAddNGSINH;
    private javax.swing.JLabel jlbAddSODT;
    private javax.swing.JLabel jlbEditDCHI;
    private javax.swing.JLabel jlbEditDOANHSO;
    private javax.swing.JLabel jlbEditHOTEN;
    private javax.swing.JLabel jlbEditLOAIKH;
    private javax.swing.JLabel jlbEditMAKH;
    private javax.swing.JLabel jlbEditNGDK;
    private javax.swing.JLabel jlbEditNGSINH;
    private javax.swing.JLabel jlbEditSODT;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JPanel jplFuntion;
    private javax.swing.JTable jtbData;
    private javax.swing.JTextField txtAddDCHI;
    private javax.swing.JTextField txtAddDOANHSO;
    private javax.swing.JTextField txtAddHOTEN;
    private javax.swing.JTextField txtAddLOAIKH;
    private javax.swing.JTextField txtAddMAKH;
    private javax.swing.JTextField txtAddNGDK;
    private javax.swing.JTextField txtAddNGSINH;
    private javax.swing.JTextField txtAddSODT;
    private javax.swing.JTextField txtEditDCHI;
    private javax.swing.JTextField txtEditDOANHSO;
    private javax.swing.JTextField txtEditHOTEN;
    private javax.swing.JTextField txtEditLOAIKH;
    private javax.swing.JTextField txtEditMAKH;
    private javax.swing.JTextField txtEditNGDK;
    private javax.swing.JTextField txtEditNGSINH;
    private javax.swing.JTextField txtEditSODT;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
