/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLBH.Panel;

import QLBH.myFunction;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class QLSP extends javax.swing.JPanel {
    

    private void loadData(){
        Connection con = myFunction.getConnection();
        
        try{
        PreparedStatement pst = con.prepareStatement("select * from SANPHAM");
        ResultSet rs =  pst.executeQuery();       
        
        DefaultTableModel tbModel = (DefaultTableModel)jtbData.getModel();        
        tbModel.setRowCount(0);
        while(rs.next()){
            String MASP = rs.getString("MASP");
            String TENSP = rs.getString("TENSP");
            String DVT = rs.getString("DVT");
            String NUOCSX = rs.getString("NUOCSX");
            String GIA = myFunction.moneyCompact(rs.getString("GIA"));
            
            String data[] = {MASP,TENSP,DVT,NUOCSX,GIA};
            tbModel.addRow(data);
        }
        con.close();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    } 
    
    private void clear(){
        txtSearch.setText("");
        txtAddMASP.setText("");
        txtAddTENSP.setText("");
        txtAddDVT.setText("");
        txtAddNUOCSX.setText("");
        txtAddGIA.setText("");
        txtEditMASP.setText("");
        txtEditTENSP.setText("");
        txtEditDVT.setText("");
        txtEditNUOCSX.setText("");
        txtEditGIA.setText("");

        loadData();  
    }
    
    public QLSP() {
        initComponents();
        loadData();
        jtbData.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDialog = new javax.swing.JDialog();
        jlbAddMASP = new javax.swing.JLabel();
        jlbAddTENSP = new javax.swing.JLabel();
        jlbAddDVP = new javax.swing.JLabel();
        jlbAddNUOCSX = new javax.swing.JLabel();
        jlbAddGIA = new javax.swing.JLabel();
        txtAddMASP = new javax.swing.JTextField();
        txtAddTENSP = new javax.swing.JTextField();
        txtAddDVT = new javax.swing.JTextField();
        txtAddNUOCSX = new javax.swing.JTextField();
        txtAddGIA = new javax.swing.JTextField();
        btnAddConfirm = new javax.swing.JButton();
        editDialog = new javax.swing.JDialog();
        jlbEditMASP = new javax.swing.JLabel();
        jlbEditTENSP = new javax.swing.JLabel();
        jlbEditDVT = new javax.swing.JLabel();
        jlbEditNUOCSX = new javax.swing.JLabel();
        jlbEditGIA = new javax.swing.JLabel();
        txtEditMASP = new javax.swing.JTextField();
        txtEditTENSP = new javax.swing.JTextField();
        txtEditDVT = new javax.swing.JTextField();
        txtEditNUOCSX = new javax.swing.JTextField();
        txtEditGIA = new javax.swing.JTextField();
        btnEditConfirm = new javax.swing.JButton();
        jlbTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbData = new javax.swing.JTable();
        jplFuntion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnRef = new javax.swing.JButton();

        addDialog.setTitle("Thêm Sản Phảm");
        addDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                addDialogWindowClosed(evt);
            }
        });

        jlbAddMASP.setText("Mã SP:");

        jlbAddTENSP.setText("Tên SP:");

        jlbAddDVP.setText("ĐVT:");

        jlbAddNUOCSX.setText("Nước SX:");

        jlbAddGIA.setText("Giá:");

        btnAddConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/check-16.png"))); // NOI18N
        btnAddConfirm.setText("Xác Nhận");
        btnAddConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDialogLayout = new javax.swing.GroupLayout(addDialog.getContentPane());
        addDialog.getContentPane().setLayout(addDialogLayout);
        addDialogLayout.setHorizontalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbAddNUOCSX)
                    .addComponent(jlbAddDVP)
                    .addComponent(jlbAddTENSP)
                    .addComponent(jlbAddMASP)
                    .addComponent(jlbAddGIA))
                .addGap(30, 30, 30)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAddGIA)
                    .addComponent(txtAddTENSP)
                    .addComponent(txtAddDVT)
                    .addComponent(txtAddNUOCSX, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddMASP, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(30, 30, 30))
            .addGroup(addDialogLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnAddConfirm)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        addDialogLayout.setVerticalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddMASP)
                    .addComponent(txtAddMASP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddTENSP)
                    .addComponent(txtAddTENSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddDVP)
                    .addComponent(txtAddDVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddNUOCSX)
                    .addComponent(txtAddNUOCSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddGIA)
                    .addComponent(txtAddGIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddConfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editDialog.setTitle("Thay đổi thông tin Sản Phảm");
        editDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                editDialogWindowClosed(evt);
            }
        });

        jlbEditMASP.setText("Mã SP:");

        jlbEditTENSP.setText("Tên SP:");

        jlbEditDVT.setText("ĐVT:");

        jlbEditNUOCSX.setText("Nước SX:");

        jlbEditGIA.setText("Giá:");

        btnEditConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/check-16.png"))); // NOI18N
        btnEditConfirm.setText("Xác Nhận");
        btnEditConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editDialogLayout = new javax.swing.GroupLayout(editDialog.getContentPane());
        editDialog.getContentPane().setLayout(editDialogLayout);
        editDialogLayout.setHorizontalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbEditNUOCSX)
                    .addComponent(jlbEditDVT)
                    .addComponent(jlbEditTENSP)
                    .addComponent(jlbEditMASP)
                    .addComponent(jlbEditGIA))
                .addGap(30, 30, 30)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEditGIA)
                    .addComponent(txtEditTENSP)
                    .addComponent(txtEditDVT)
                    .addComponent(txtEditNUOCSX, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEditMASP, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDialogLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(btnEditConfirm)
                .addGap(136, 136, 136))
        );
        editDialogLayout.setVerticalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditMASP)
                    .addComponent(txtEditMASP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditTENSP)
                    .addComponent(txtEditTENSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditDVT)
                    .addComponent(txtEditDVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditNUOCSX)
                    .addComponent(txtEditNUOCSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEditGIA)
                    .addComponent(txtEditGIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEditConfirm)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jlbTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbTitle.setForeground(new java.awt.Color(0, 153, 153));
        jlbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitle.setText("QUẢN LÝ SẢN PHẨM");

        jtbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "ĐVT", "Nước SX", "Giá"
            }
        ));
        jScrollPane1.setViewportView(jtbData);

        jplFuntion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tìm Kiếm:");

        txtSearch.setPreferredSize(new java.awt.Dimension(64, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/search.png"))); // NOI18N
        jButton1.setText("Tìm Kiếm");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/add.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setPreferredSize(new java.awt.Dimension(100, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/edit.png"))); // NOI18N
        btnMod.setText("Sửa");
        btnMod.setPreferredSize(new java.awt.Dimension(100, 30));
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/delete.png"))); // NOI18N
        btnDel.setText("Xóa");
        btnDel.setPreferredSize(new java.awt.Dimension(100, 30));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnRef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLBH/img/clear.png"))); // NOI18N
        btnRef.setText("Làm Mới");
        btnRef.setPreferredSize(new java.awt.Dimension(100, 30));
        btnRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplFuntionLayout = new javax.swing.GroupLayout(jplFuntion);
        jplFuntion.setLayout(jplFuntionLayout);
        jplFuntionLayout.setHorizontalGroup(
            jplFuntionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplFuntionLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addComponent(jSeparator2)
            .addGroup(jplFuntionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplFuntionLayout.setVerticalGroup(
            jplFuntionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplFuntionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplFuntionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jplFuntionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(jplFuntion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jplFuntion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addDialog.pack();
        addDialog.setSize(375, 350);
        addDialog.setLocationRelativeTo(null);
        addDialog.setAlwaysOnTop(true);
        addDialog.setModal(true);
        addDialog.setVisible(true);
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAddConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddConfirmActionPerformed
        StringBuilder sbError = new StringBuilder();
        if(txtAddMASP.getText().hashCode() == 0) sbError.append("Yêu cầu có mã Sản Phẩm! \n");
        if(txtAddMASP.getText().length()>4) sbError.append("Mã Sản Phẩm tối đa 4 kí tự, ví dụ NV01 NV02 ... \n");
               
        Connection con = myFunction.getConnection();
        try{
            if(sbError.length()>0) JOptionPane.showMessageDialog(addDialog, sbError ,"Thông Báo",HEIGHT);
        else{
            String query = "INSERT INTO SANPHAM VALUES (?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, txtAddMASP.getText());
            pst.setString(2, txtAddTENSP.getText());
            pst.setString(3, txtAddDVT.getText());
            pst.setString(4, txtAddNUOCSX.getText());
            pst.setString(5, txtAddGIA.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(addDialog, "Ðã thêm thành công!");
            clear();
            con.close();
            addDialog.dispose();
        }
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            JOptionPane.showMessageDialog(addDialog, e);
        }
    }//GEN-LAST:event_btnAddConfirmActionPerformed

    private void addDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_addDialogWindowClosed
        addDialog.dispose();
    }//GEN-LAST:event_addDialogWindowClosed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        editDialog.pack();
        editDialog.setSize(375, 350);
        editDialog.setAlwaysOnTop(true);
        editDialog.setModal(true);
        editDialog.setLocationRelativeTo(this);
        txtEditMASP.setEnabled(false);
        
        DefaultTableModel recordModel = (DefaultTableModel)jtbData.getModel();
        int selectdRow = jtbData.getSelectedRow();
        if(selectdRow==-1) JOptionPane.showMessageDialog(null, "Hãy chọn dữ liệu cần thay đổi!" ,"Thông Báo",HEIGHT);
        else{
            txtEditMASP.setText(recordModel.getValueAt(selectdRow, 0).toString());
            if(recordModel.getValueAt(selectdRow, 1)!=null)
            txtEditTENSP.setText(recordModel.getValueAt(selectdRow, 1).toString());
            if(recordModel.getValueAt(selectdRow, 2)!=null)
            txtEditDVT.setText(recordModel.getValueAt(selectdRow, 2).toString());
            if(recordModel.getValueAt(selectdRow, 3)!=null)
            txtEditNUOCSX.setText(recordModel.getValueAt(selectdRow, 3).toString());
            if(recordModel.getValueAt(selectdRow, 4)!=null)
            txtEditGIA.setText(recordModel.getValueAt(selectdRow, 4).toString());


            editDialog.setAlwaysOnTop(true);
            editDialog.setModal(true);
            editDialog.setLocationRelativeTo(this);

            editDialog.setVisible(true);
        }
    }//GEN-LAST:event_btnModActionPerformed

    private void editDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_editDialogWindowClosed
        editDialog.dispose();
    }//GEN-LAST:event_editDialogWindowClosed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        DefaultTableModel recordModel = (DefaultTableModel)jtbData.getModel();
        int selectdRow = jtbData.getSelectedRow();
        if(selectdRow==-1) JOptionPane.showMessageDialog(null, "Hãy chọn dữ liệu cần xóa!" ,"Thông Báo",HEIGHT);
        else{
        int response = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?", "Xác Nhận Xóa", WIDTH, HEIGHT);
        if(response==JOptionPane.YES_OPTION)
        {
        Connection con = myFunction.getConnection();
        try{
        String query = "DELETE FROM SANPHAM WHERE MASP=?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, recordModel.getValueAt(selectdRow, 0).toString());
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Ðã xóa thành công!");
        loadData();
        con.close();
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefActionPerformed
        clear();
    }//GEN-LAST:event_btnRefActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = myFunction.getConnection();
        try{
        String query = "select * from SANPHAM where MASP = '" + txtSearch.getText() + "' or TENSP LIKE N'%" + txtSearch.getText() + "%'" ;
        PreparedStatement pst = con.prepareStatement(query);
        ResultSet rs =  pst.executeQuery();
        
        DefaultTableModel rsModel = (DefaultTableModel)jtbData.getModel();
        
        rsModel.setRowCount(0);
        while(rs.next()){
            String MASP = rs.getString("MASP");
            String TENSP = rs.getString("TENSP");
            String DVT = rs.getString("DVT");
            String NUOCSX = rs.getString("NUOCSX");
            String GIA = myFunction.moneyCompact(rs.getString("GIA"));
            
            String data[] = {MASP,TENSP,DVT,NUOCSX,GIA};
            rsModel.addRow(data);
        }
        con.close();
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEditConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditConfirmActionPerformed
        StringBuilder sbError = new StringBuilder();
        if(txtEditMASP.getText().hashCode() == 0) sbError.append("Yêu cầu có mã Sản Phẩm! \n");
        if(txtEditMASP.getText().length()>4) sbError.append("Mã Sản Phẩm tối đa 4 kí tự, ví dụ NV01 NV02 ... \n");
       
        Connection con = myFunction.getConnection();
        if(sbError.length()>0) JOptionPane.showMessageDialog(editDialog, sbError ,"Thông Báo",HEIGHT);
        else{
            try{
                String query = "UPDATE SANPHAM SET TENSP = ?, DVT = ?, NUOCSX = ?,GIA = ? WHERE MASP = ?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, txtEditTENSP.getText());
                pst.setString(2, txtEditDVT.getText());
                pst.setString(3, txtEditNUOCSX.getText());
                pst.setString(4, txtEditGIA.getText());
                pst.setString(5, txtEditMASP.getText());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(editDialog, "Ðã cập nhật thành công!");
                clear();
                con.close();
                editDialog.dispose();
            }
            // Handle any errors that may have occurred.
            catch (SQLException e) {
                JOptionPane.showMessageDialog(editDialog, e);
            }
        }
    }//GEN-LAST:event_btnEditConfirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog addDialog;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddConfirm;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEditConfirm;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnRef;
    private javax.swing.JDialog editDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlbAddDVP;
    private javax.swing.JLabel jlbAddGIA;
    private javax.swing.JLabel jlbAddMASP;
    private javax.swing.JLabel jlbAddNUOCSX;
    private javax.swing.JLabel jlbAddTENSP;
    private javax.swing.JLabel jlbEditDVT;
    private javax.swing.JLabel jlbEditGIA;
    private javax.swing.JLabel jlbEditMASP;
    private javax.swing.JLabel jlbEditNUOCSX;
    private javax.swing.JLabel jlbEditTENSP;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JPanel jplFuntion;
    private javax.swing.JTable jtbData;
    private javax.swing.JTextField txtAddDVT;
    private javax.swing.JTextField txtAddGIA;
    private javax.swing.JTextField txtAddMASP;
    private javax.swing.JTextField txtAddNUOCSX;
    private javax.swing.JTextField txtAddTENSP;
    private javax.swing.JTextField txtEditDVT;
    private javax.swing.JTextField txtEditGIA;
    private javax.swing.JTextField txtEditMASP;
    private javax.swing.JTextField txtEditNUOCSX;
    private javax.swing.JTextField txtEditTENSP;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
